/*
 * DIO_Config.h
 *
 *  Created on: Aug 10, 2017
 *      Author: Mahmoud Ewaisha
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_


#define DIO_PIN0DIRECTION    DIO_INPUT
#define DIO_PIN1DIRECTION    DIO_INPUT
#define DIO_PIN2DIRECTION    DIO_INPUT
#define DIO_PIN3DIRECTION    DIO_INPUT
#define DIO_PIN4DIRECTION    DIO_INPUT
#define DIO_PIN5DIRECTION    DIO_INPUT
#define DIO_PIN6DIRECTION    DIO_INPUT
#define DIO_PIN7DIRECTION    DIO_INPUT
#define DIO_PIN8DIRECTION    DIO_INPUT
#define DIO_PIN9DIRECTION    DIO_INPUT
#define DIO_PIN10DIRECTION   DIO_INPUT
#define DIO_PIN11DIRECTION   DIO_INPUT
#define DIO_PIN12DIRECTION   DIO_INPUT
#define DIO_PIN13DIRECTION   DIO_INPUT
#define DIO_PIN14DIRECTION   DIO_INPUT
#define DIO_PIN15DIRECTION   DIO_INPUT
#define DIO_PIN16DIRECTION   DIO_INPUT
#define DIO_PIN17DIRECTION   DIO_INPUT
#define DIO_PIN18DIRECTION   DIO_INPUT
#define DIO_PIN19DIRECTION   DIO_INPUT
#define DIO_PIN20DIRECTION   DIO_INPUT
#define DIO_PIN21DIRECTION   DIO_INPUT
#define DIO_PIN22DIRECTION   DIO_INPUT
#define DIO_PIN23DIRECTION   DIO_INPUT
#define DIO_PIN24DIRECTION   DIO_INPUT
#define DIO_PIN25DIRECTION   DIO_INPUT
#define DIO_PIN26DIRECTION   DIO_INPUT
#define DIO_PIN27DIRECTION   DIO_INPUT
#define DIO_PIN28DIRECTION   DIO_INPUT
#define DIO_PIN29DIRECTION   DIO_INPUT
#define DIO_PIN30DIRECTION   DIO_INPUT
#define DIO_PIN31DIRECTION   DIO_INPUT



#define DIO_PIN0_INITIAL_VALUE    DIO_LOW
#define DIO_PIN1_INITIAL_VALUE    DIO_LOW
#define DIO_PIN2_INITIAL_VALUE    DIO_LOW
#define DIO_PIN3_INITIAL_VALUE    DIO_LOW
#define DIO_PIN4_INITIAL_VALUE    DIO_LOW
#define DIO_PIN5_INITIAL_VALUE    DIO_LOW
#define DIO_PIN6_INITIAL_VALUE    DIO_LOW
#define DIO_PIN7_INITIAL_VALUE    DIO_LOW
#define DIO_PIN8_INITIAL_VALUE    DIO_LOW
#define DIO_PIN9_INITIAL_VALUE    DIO_LOW
#define DIO_PIN10_INITIAL_VALUE   DIO_LOW
#define DIO_PIN11_INITIAL_VALUE   DIO_LOW
#define DIO_PIN12_INITIAL_VALUE   DIO_LOW
#define DIO_PIN13_INITIAL_VALUE   DIO_LOW
#define DIO_PIN14_INITIAL_VALUE   DIO_LOW
#define DIO_PIN15_INITIAL_VALUE   DIO_LOW
#define DIO_PIN16_INITIAL_VALUE   DIO_LOW
#define DIO_PIN17_INITIAL_VALUE   DIO_LOW
#define DIO_PIN18_INITIAL_VALUE   DIO_LOW
#define DIO_PIN19_INITIAL_VALUE   DIO_LOW
#define DIO_PIN20_INITIAL_VALUE   DIO_LOW
#define DIO_PIN21_INITIAL_VALUE   DIO_LOW
#define DIO_PIN22_INITIAL_VALUE   DIO_LOW
#define DIO_PIN23_INITIAL_VALUE   DIO_LOW
#define DIO_PIN24_INITIAL_VALUE   DIO_LOW
#define DIO_PIN25_INITIAL_VALUE   DIO_LOW
#define DIO_PIN26_INITIAL_VALUE   DIO_LOW
#define DIO_PIN27_INITIAL_VALUE   DIO_LOW
#define DIO_PIN28_INITIAL_VALUE   DIO_LOW
#define DIO_PIN29_INITIAL_VALUE   DIO_LOW
#define DIO_PIN30_INITIAL_VALUE   DIO_LOW
#define DIO_PIN31_INITIAL_VALUE   DIO_LOW



#endif /* DIO_CONFIG_H_ */
